Keras practice

In [1]:
#importing libraries needed for generating data to play with
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler



In [2]:
train_labels = []
train_samples = []


DESCRIPTION OF DATA

An experimental drug was tested on individuals from ages 13 to 65
the trial had 2100 participants. Half were under 65.
95% of patients 65 or older experienced side effects
95% if patients under 65 experienced no side effects

In [3]:
for i in range(1000):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)
    
for i in range(50):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

In [38]:
train_samples

array([64, 84, 19, ..., 68, 48, 99])

In [4]:
#keras accepts format of a numpy array, so changing the data to the acceptable format

train_labels = np.array(train_labels)
train_samples = np.array(train_samples)

In [5]:
scaler = MinMaxScaler(feature_range=(0,1)) #converts the data to fit into the interval 0 and 1
scaled_train_samples = scaler.fit_transform((train_samples).reshape(-1,1)) #using reshape, to be able to put there 1D data

/home/kodolamacz/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


In [41]:
scaled_train_samples

array([[ 0.5862069 ],
       [ 0.81609195],
       [ 0.06896552],
       ..., 
       [ 0.63218391],
       [ 0.40229885],
       [ 0.98850575]])

Importing all the keras stuff :)

In [6]:
import keras

from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy


Using TensorFlow backend.


In [23]:
#constructing the model

model = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='relu')
])

In [24]:
#visualising the model for better understanding
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 16)                32        
_________________________________________________________________
dense_20 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_21 (Dense)             (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [25]:
#model.compile(Optimizer)
model.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [27]:
#now train the model, using the .fit function

model.fit(scaled_train_samples, train_labels, validation_split = 0.1, batch_size=10, epochs=20, shuffle=True, verbose=2)

Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 2/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 3/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 4/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 5/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 6/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 7/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 8/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 9/20
 - 1s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 10/20
 - 1s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 11/20
 - 0s - loss: 0.6931 - acc: 0.5000 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 12/20
 - 0s - loss: 0.6931 - acc

In [31]:
test_labels = []
test_samples = []

In [32]:
#make some test data to check how well does the model perform

for i in range(200):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)
    
for i in range(10):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)

In [33]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

In [34]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1,1))

/home/kodolamacz/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


In [42]:
#Predictions

predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)
predictions

#something seems amiss

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [43]:
predictions_classes = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)
predictions_classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [45]:
#create a confusion matrix to have a representation how well our model did.
#to do so, importing the necessary packages

%matplotlib inline
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt



In [48]:
cm = confusion_matrix(test_labels, predictions_classes)
cm

array([[210,   0],
       [210,   0]])

In [ ]:
#now save the model for future re-use

In [50]:
model.save('medical_trial_model.h5')



In [51]:
from keras.models import load_model
new_model = load_model('medical_trial_model.h5')

In [52]:
new_model.get_weights() #checking the weights of the saved model

[array([[-0.34251383,  0.563169  , -0.05200577,  0.58211291, -0.50965744,
         -0.05157685, -0.19543064, -0.09053445,  0.39342797, -0.37048143,
         -0.33797294,  0.14813787,  0.35797727, -0.2944161 ,  0.05691701,
          0.25962746]], dtype=float32),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.], dtype=float32),
 array([[-0.19500689, -0.29259303,  0.02152979, -0.26839358, -0.13782045,
          0.19900998, -0.30913886,  0.15817544, -0.18546939,  0.26179203,
         -0.02124253,  0.3387005 , -0.3472923 , -0.01294002, -0.25900689,
          0.34685144, -0.32633325, -0.19331646,  0.32023385, -0.21607703,
         -0.26793307,  0.22866586,  0.22609088,  0.30062392, -0.07625991,
         -0.19244032, -0.21402793, -0.08554277, -0.08894461, -0.02174011,
         -0.06904909,  0.04303664],
        [ 0.12091711, -0.06850481,  0.32583222,  0.3020514 ,  0.10607341,
         -0.16770197,  0.2158514 , -0.08850029, -0.07285368, -0.2660050

In [54]:
new_model.optimizer #the same optimizer :)

In [ ]:
#it is also possible to save ONLY the architecture of the model by using model.to_json()

In [ ]:
#or you can save only the weights of the file by using model.save_weights('my_model_weights.h5')